// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxbfW7WGxETJmj2UIpGLQbn2HlXTe3FuA',
    appId: '1:260007153522:android:ff9139cc75f95c9a0d17eb',
    messagingSenderId: '260007153522',
    projectId: 'myblueboard-f559b',
    storageBucket: 'myblueboard-f559b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA95jMpCFBaKGMkeFQQ8o_yxuVPmjxm7Io',
    appId: '1:260007153522:ios:bdde228642222c280d17eb',
    messagingSenderId: '260007153522',
    projectId: 'myblueboard-f559b',
    storageBucket: 'myblueboard-f559b.firebasestorage.app',
    iosBundleId: 'com.myblueboard.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA95jMpCFBaKGMkeFQQ8o_yxuVPmjxm7Io',
    appId: '1:260007153522:ios:bdde228642222c280d17eb',
    messagingSenderId: '260007153522',
    projectId: 'myblueboard-f559b',
    storageBucket: 'myblueboard-f559b.firebasestorage.app',
    iosBundleId: 'com.myblueboard.admin',
  );

}